#!/usr/bin/env bash

ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rlwrap jdb -classpath "$ROOTDIR/build/tests/:$ROOTDIR/build/jar/*:$ROOTDIR/real-libs/*:$ROOTDIR/run-libs/*" -sourcepath "$ROOTDIR/src/" $1 ${@:2}
